---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ja-rental-backend
data:
  APP_ID: ${APP_ID}
  PORT: ${PORT}
  LOG_LEVEL: ${LOG_LEVEL}
  REQUEST_LIMIT: ${REQUEST_LIMIT}
  SESSION_SECRET: ${SESSION_SECRET}
  OPENAPI_SPEC: ${OPENAPI_SPEC}
  MONGO_HOST: ${MONGO_HOST}
  MONGO_PORT: ${MONGO_PORT}
  MONGO_DB: ${MONGO_DB}
  SCRAPER_CRON_SCHEDULE: ${SCRAPER_CRON_SCHEDULE}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ja-rental-backend
  labels:
    app: ja-rental-backend
spec:
  selector:
    matchLabels:
      app: ja-rental-backend
      tier: web
  template:
    metadata:
      labels:
        app: ja-rental-backend
        tier: web
        sha: ${SHORT_SHA}
    spec:
      containers:
      - name: ja-rental-backend
        image: gcr.io/website-227817/ja-rentals-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: APP_ID
          valueFrom:
            configMapKeyRef:
              name: ja-rental-backend
              key: APP_ID
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ja-rental-backend
              key: PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ja-rental-backend
              key: LOG_LEVEL
        - name: REQUEST_LIMIT
          valueFrom:
            configMapKeyRef:
              name: ja-rental-backend
              key: REQUEST_LIMIT
        - name: SESSION_SECRET
          valueFrom:
            configMapKeyRef:
              name: ja-rental-backend
              key: SESSION_SECRET
        - name: OPENAPI_SPEC
          valueFrom:
            configMapKeyRef:
              name: ja-rental-backend
              key: OPENAPI_SPEC
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: ja-rental-backend
              key: MONGO_HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: ja-rental-backend
              key: MONGO_PORT
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: ja-rental-backend
              key: MONGO_DB
        - name: SCRAPER_CRON_SCHEDULE
          valueFrom:
            configMapKeyRef:
              name: ja-rental-backend
              key: SCRAPER_CRON_SCHEDULE
---
apiVersion: v1
kind: Service
metadata:
  name: ja-rental-backend
  labels:
    app: ja-rental-backend
spec:
  type: NodePort
  selector:
    app: ja-rental-backend
    tier: web
  ports:
  - port: 8080
    targetPort: 8080

          